apiVersion: v1
kind: Service
metadata:
  name: titanic-service
  namespace: titanic
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30001
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: titanic-app
