#namespace titanic
apiVersion: v1
kind: Namespace
metadata:
  name: titanic
  labels:
    name: titanic

---

apiVersion: v1
kind: Secret
metadata:
  name: titanic-api-creds
  namespace: titanic
data:
  CLOUDKARAFKA_USERNAME: SldVNUZJUFJaRlFPT1FFVw==
  CLOUDKARAFKA_PASSWORD: Mk1XZXhCanFBNitwa3B6SnNVM2FDN0lydkR2a3F6Vy9FbXNrd08rUGVaM0JwRVU0WFYwRitiSDBhM0J5MHB0Qw==