

apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-app
  namespace: titanic
  labels:
    app: titanic-app
spec:
  selector:
    matchLabels:
      app: titanic-app
  template:
    metadata:
      labels:
        app: titanic-app
    spec:
      containers:
      - name: titanic-app
        image: couchoudma/titanic:latest
        envFrom:
          - secretRef:
              name: titanic-api-creds
        ports:
        - containerPort: 80
          protocol: TCP
        
        


